# Python 3.11 베이스 이미지
FROM python:3.11

# 필수 패키지 설치
RUN apt-get update && apt-get install -y wget gnupg2 unzip jq \
    libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 \
    libnss3 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libgtk-3-0 \
    libgbm-dev fonts-liberation libappindicator3-1 xdg-utils \
    && apt-get clean

# /opt/google/chrome 디렉터리에 Chrome 설치
RUN mkdir -p /opt/google/chrome \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && dpkg -x google-chrome-stable_current_amd64.deb /opt/google/chrome \
    && ln -s /opt/google/chrome/opt/google/chrome/google-chrome /usr/bin/google-chrome \
    && rm google-chrome-stable_current_amd64.deb

# Chrome 실행 경로를 /opt/google/chrome/google-chrome 으로 설정
ENV CHROME_BIN=/opt/google/chrome/opt/google/chrome/google-chrome
ENV CHROME_DRIVER=/opt/chrome/chromedriver

# ChromeDriver 설치 (Chrome의 Major 버전과 일치)
RUN CHROME_VERSION=$($CHROME_BIN --version | cut -d ' ' -f 3) \
    && DRIVER_URL=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json \
        | jq -r --arg version "$CHROME_VERSION" '.versions[] | select(.version==$version) | .downloads.chromedriver[] | select(.platform=="linux64").url') \
    && if [ -z "$DRIVER_URL" ]; then \
        echo "ChromeDriver URL을 찾지 못했습니다. 빌드를 중단합니다." \
        && exit 1; \
    fi \
    && wget -O /tmp/chromedriver.zip "$DRIVER_URL" \
    && unzip /tmp/chromedriver.zip -d /opt/chrome/ \
    && chmod +x /opt/chrome/chromedriver \
    && rm -rf /tmp/chromedriver-linux64 \
    && rm /tmp/chromedriver.zip

# 권한 설정 (Chrome 및 ChromeDriver)
RUN chmod -R 755 /opt/chrome/chromedriver && chmod -R 755 /opt/google/chrome

# Python 종속성 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# PYTHONPATH 설정
ENV PYTHONPATH=/app

# 작업 디렉토리 설정
WORKDIR /app

# 프로젝트 파일 복사
COPY . .

# 크롬 실행 시 추가로 --no-sandbox 옵션을 사용
CMD ["python3", "/app/app/data_upload/crawl_update_daily_data.py", "--no-sandbox"]
